<div style="border:solid green 2px; padding: 20px"> <h1 style="color:green; margin-bottom:20px">Комментарий ревьюера</h1>

Привет! Меня зовут - Сысоева Вера.
    
Далее в файле мои комментарии ты сможешь найти в ячейках, аналогичных данной ( если рамки комментария зелёные - всё сделано правильно; жёлтые - есть замечания, но не критично; красные - нужно переделать). Не удаляй эти комментарии и постарайся учесть их в ходе выполнения проекта.
    
Я буду поддерживать версионность комментариев, и при следующих итерациях комментарии будут выделены, как "Комментраии ревьюера - 2 (3 и.т.д.)"
    
Если у тебя есть замечания, возражения и вопросы, ты можшь писать свои комментарии, по возможности выделяй их также цветом (например, синим), чтоб их можно было легко отделить от текста проекта. 
    
Кстати, предлагаю сразу общаться на "ты".
</div>

# Ответ
Привет, Вера! Меня зовут Дмитрий! Давай на "ты")
Для меня это первый проект, в аналитике я новичок. Стараюсь разобраться в материалах и заданиях, но теоретического курса мало для каких-либо выводов. Пока непонятно, насколько детально надо описывать ход мыслей и действий. Я постарался все исправить и дать более подробные комментарии по ходу своих решений. 
Из проблем - блокнот. Как смог внес изменения, но по выделениям и цветам не получается. Как по мне, он не очень удобен для оформления.
И не удалось в цикле почситать число значений по словам для вероятности невозврата кредита. Как итог методом count() пробегал по столбцу и получились громоздкие вычисления. Но зато результат получен)


<div style="border:solid green 2px; padding: 20px"> <h1 style="color:green; margin-bottom:20px">Комментарий ревьюера - 2</h1>

Оформлять текст можно языком Markdown http://ilfire.ru/kompyutery/shpargalka-po-sintaksisu-markdown-markdaun-so-vsemi-samymi-populyarnymi-tegami/
    
А можно в тех же ячейках с использованием HTML тегов, выделение цветом - это сюда    
</div>

## Исследование надёжности заёмщиков

Заказчик — кредитный отдел банка. Нужно разобраться, влияет ли семейное положение и количество детей клиента на факт погашения кредита в срок. Входные данные от банка — статистика о платёжеспособности клиентов.

Результаты исследования будут учтены при построении модели **кредитного скоринга** — специальной системы, которая оценивает способность потенциального заёмщика вернуть кредит банку.

<div style="border:solid green 2px; padding: 20px"> <h1 style="color:green; margin-bottom:20px">Комментарий ревьюера</h1>

Описание целей и задач проекта очень важно, не забудь про эту часть в следующих проектах, когда не будет такого подробного шаблона.
    
Также удобно вначале следать интерактивное оглавление.
    
Само оглавление делаешь по такому типу:  
1. [Шаг 1. Откроем файл с данными и изучим общую информацию](#step1)  
2. [Шаг 2](#step2)  

А в заголовках оставляешь метки вот так:  
### Шаг 1. Откроем файл с данными и изучим общую информацию <a id="step1"></a>   
    
    
    
Это сильно повышает привлекательность проекта.
</div>

### Шаг 1. Откроем файл с данными и изучим общую информацию. 

In [6]:
# <импорт библиотеки pandas>
import pandas as pd 
# <чтение файла с данными с сохранением в df>
df = pd.read_csv('/datasets/data.csv') 
#print(df.head(10))
df.info()

#уникальные данные по количеству детей в семье
unique_children = df['children'].unique()
print('Данные по количеству детей в семье:',unique_children)

#уникальные семейное положение
unique_family_status = df['family_status'].unique()
print('Cемейное положение:',unique_family_status)

#уникальные данные по задолженности по возврату кредита
unique_debt = df['debt'].unique()
print('Задолженности по возврату кредита:',unique_debt)

#уникальные цели получения кредита
#unique_purpose = df['purpose'].unique()
#print(unique_purpose)

#уникальный тип занятости
#unique_income_type = df['income_type'].unique()
#print(unique_income_type)

#df.shape
#df.style.format("{:.2%}") 'debt': '{:+.2f}'
#df.style.format({'debt': '{:.2%}'})

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
children            21525 non-null int64
days_employed       19351 non-null float64
dob_years           21525 non-null int64
education           21525 non-null object
education_id        21525 non-null int64
family_status       21525 non-null object
family_status_id    21525 non-null int64
gender              21525 non-null object
income_type         21525 non-null object
debt                21525 non-null int64
total_income        19351 non-null float64
purpose             21525 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB
Данные по количеству детей в семье: [ 1  0  3  2 -1  4 20  5]
Cемейное положение: ['женат / замужем' 'гражданский брак' 'вдовец / вдова' 'в разводе'
 'Не женат / не замужем']
Задолженности по возврату кредита: [0 1]


In [10]:
df.loc[df['total_income'].isna(),'total_income']

12      NaN
26      NaN
29      NaN
41      NaN
55      NaN
         ..
21489   NaN
21495   NaN
21497   NaN
21502   NaN
21510   NaN
Name: total_income, Length: 2174, dtype: float64

### Вывод

В данных по количеству детей в семье присутствуют значения '-1' и '20', что является неправдоподомным.
days_employed — общий трудовой стаж в днях данные в столбце как положительные, так и отрицательные. На анализ данных не влияют. Данный столбец не трогаем.
total_income — ежемесячный доход отсутствуют значения (около 10%)


<div style="border:solid green 2px; padding: 20px"> <h1 style="color:green; margin-bottom:20px">Комментарий ревьюера</h1>

Отлично, ты все верно отметил. Правильно использованы info() и unique, можно переходить к предобработке
    
Для просмотра содержимого всех столбцов можно было unique пройти в цикле
    
Отлично, что ты посчитал процент пропусков
</div>

Шаг 2. Предобработка данных

### Шаг 2. Обработываем пропуски

In [3]:
#общий трудовой стаж в днях
#пропуски будем заменять на среднее значение
days_employed_avg = df['days_employed'].median()
print('Медианное значение трудового стажа в днях',days_employed_avg)
#df['days_employed'] = df['days_employed'].fillna(value=days_employed_avg)
df['days_employed'] = df['days_employed'].fillna(0)
print(df.head(100))
#df.info()

#ежемесячный доход
#пропуски будем заменять на среднее значение
total_income_avg = df['total_income'].median()
print('Медианное значение ежемесячного дохода',total_income_avg)
df['total_income'] = df['total_income'].fillna(0)
#print(df.head(10))
df.info()

Медианное значение трудового стажа в днях -1203.369528770489
    children  days_employed  dob_years education  education_id  \
0          1   -8437.673028         42    высшее             0   
1          1   -4024.803754         36   среднее             1   
2          0   -5623.422610         33   Среднее             1   
3          3   -4124.747207         32   среднее             1   
4          0  340266.072047         53   среднее             1   
..       ...            ...        ...       ...           ...   
95         0    -541.832241         51    высшее             0   
96         0       0.000000         44   СРЕДНЕЕ             1   
97         0       0.000000         47    высшее             0   
98         0  364906.205736         54    высшее             0   
99         0  346541.618895          0   Среднее             1   

       family_status  family_status_id gender income_type  debt  \
0    женат / замужем                 0      F   сотрудник     0   
1    женат /

### Вывод

Таблица полностью заполнена. Приступаем к обработке данных по количеству детей в семье


<div style="border:solid gold 2px; padding: 20px"> <h1 style="color:gold; margin-bottom:20px">Комментарий ревьюера</h1>

пропусков нет - это хорошо, плохо, что ты это никак не прокомментировал. Да и заполнение средним - не самый лучший вариант. А вот если бы ты сам для себя обосновал выбор среднего как способа заполнения, то возможно пришел бы к тому же выводу. 
    
Стаж и доход подвержены выбросам, а значит лучше для восстановления данных выбрать медиану
</div>

# Ответ 
Применяем медианное значение. 
В теории применение этих значений упоминается вскользь, поэтому мне непонятно, в каких ситуациях надо применять среднее, а в каких медианное. Теперь буду знать.
Для значений трудового стажа не влияет, какие значения мы будем использовать, т.к. в ответах на вопросы столбец days_employed не учавствует. 

<div style="border:solid green 2px; padding: 20px"> <h1 style="color:green; margin-bottom:20px">Комментарий ревьюера - 2</h1>

Хорошо, так правильнее
</div>

### Шаг 3. Заменяем тип данных

In [3]:
# определим уникалые значения столбца - количество детей в семье
#print(df['children'].value_counts())
# значение -1 относится к ошибочному вводу данных.  Удалим строки содержащие данные числа. 47 строк из 21525 не повлияют на анализ наших данны
# значение 20 - относится к ошибочному вводу данных. Удалим строки содержащие данные числа. 76 строк из 214785 не повлияют на анализ наших данных

df['days_employed'] = df['days_employed'].astype('int')
#df.dtypes
df['total_income'] = df['total_income'].astype('int')
df.dtypes
#print(df)
df_c = df[df['children'] >= 0]
#df_c.info()
df = df_c[df_c['children'] <= 4]
df.info()


<class 'pandas.core.frame.DataFrame'>
Int64Index: 21393 entries, 0 to 21524
Data columns (total 12 columns):
children            21393 non-null int64
days_employed       21393 non-null int64
dob_years           21393 non-null int64
education           21393 non-null object
education_id        21393 non-null int64
family_status       21393 non-null object
family_status_id    21393 non-null int64
gender              21393 non-null object
income_type         21393 non-null object
debt                21393 non-null int64
total_income        21393 non-null int64
purpose             21393 non-null object
dtypes: int64(7), object(5)
memory usage: 2.1+ MB


### Вывод

Значения в таблице соответствуют своим строковым и числовым значениям


<div style="border:solid gold 2px; padding: 20px"> <h1 style="color:gold; margin-bottom:20px">Комментарий ревьюера</h1>

Типы данных заменены верно
    
Также аномалии хорошо обработаны, хотя это и не относится к замене типов данных и стоило сделать в другом разделе, например, в предадущем. Подобные аномалии можно считать неявными пропусками.
    
И опять же недостаточно пояснений и обоснований твоих действий. Старайся не писать пояснения комментариями в коде - это не верно и не соответствует требованиям к оформлению. Комментарии в коде - это твои заметки. Все значимые пояснения нужно делать в отдельных текстовых Markdown-ячейках
</div>

# Ответ

После обработки нашей таблицы на пропуски приступаем к ее дальнейшему изучению:
Рассмотрим столбец children:
в нем присутствуют значения "-1". Скорее всего, они относятся к ошибочному вводу данных.  Удалим строки, содержащие данные числа. 47 строк из 21525 не повлияют на анализ наших данных.
Далее в нашем столбце есть значения "20". Они относится к ошибочному вводу данных. Удалим строки, содержащие данные числа. 76 строк не повлияют на анализ наших данных
Рассмотрим столбец days_employed:
Данный столбец относится к float64. Данные с общим трудовым стажем в днях выглядят подозрительно). Присвоим этому столбцу тип int64.
Аналогичная ситуация со столбцом total_income — ежемесячный доход. Присвоим этому столбцу тип int64.

# Ответ_3
Уберем аномальные данные с 100% возвратом кредита для заемщиков с 5-ю детьми

### Шаг 4. Обработываем дубликаты

In [4]:
#Проверим на наличие дубликатов столбец purpose

#df_new.info()
#print ('Дубликатов в таблице:', df.duplicated('purpose').sum())
#print(df['purpose'].value_counts())
print('Количество дубликатов:')
print(df.duplicated().sum())
df = df.drop_duplicates().reset_index(drop=True) 

print('Сумма по значениям столбца education')
print(df['education'].value_counts())
df['education'] = df['education'].replace('Ученая степень', 'ученая степень')
df['education'] = df['education'].replace('УЧЕНАЯ СТЕПЕНЬ', 'ученая степень')
df['education'] = df['education'].replace('НАЧАЛЬНОЕ', 'начальное')
df['education'] = df['education'].replace('Начальное', 'начальное')
df['education'] = df['education'].replace('ВЫСШЕЕ', 'высшее')
df['education'] = df['education'].replace('Высшее', 'высшее')
df['education'] = df['education'].replace('НЕОКОНЧЕННОЕ ВЫСШЕЕ', 'неоконченное высшее')
df['education'] = df['education'].replace('Неоконченное высшее', 'неоконченное высшее')
df['education'] = df['education'].replace('СРЕДНЕЕ', 'среднее')
df['education'] = df['education'].replace('Среднее', 'среднее')
print(df['education'].value_counts())

print('Количество дубликатов после обработки столбца education:')
print(df.duplicated().sum())

df = df.drop_duplicates().reset_index(drop=True) 
print('Количество дубликатов после обработки дубликатов столбца education:')
print(df.duplicated().sum())

Количество дубликатов:
54
Сумма по значениям столбца education
среднее                13614
высшее                  4690
СРЕДНЕЕ                  766
Среднее                  703
неоконченное высшее      665
ВЫСШЕЕ                   270
Высшее                   268
начальное                250
Неоконченное высшее       47
НЕОКОНЧЕННОЕ ВЫСШЕЕ       29
НАЧАЛЬНОЕ                 16
Начальное                 15
ученая степень             4
Ученая степень             1
УЧЕНАЯ СТЕПЕНЬ             1
Name: education, dtype: int64
среднее                15083
высшее                  5228
неоконченное высшее      741
начальное                281
ученая степень             6
Name: education, dtype: int64
Количество дубликатов после обработки столбца education:
17
Количество дубликатов после обработки дубликатов столбца education:
0


### Вывод

Дубликатов в таблице: 21364
Возможно данные заемщиками записываются самостоятельно, для упрощения можно ввести таблицу с целями.


<div style="border:solid red 2px; padding: 20px"> <h1 style="color:red; margin-bottom:20px">Комментарий ревьюера</h1>

Не верно обработаны дубликаты. Ты посотрел дубли только в одном столбце, а не во всей таблице. Естественно в одном столбце далеко не все значения уникальны. А что можно сказать про всю таблицу? Сколько всего дублей? Каковы источники дбликатов? Что мы сними будем делать?
</div>

# Ответ
Определим одинаковые строки с идентичной информацией методом duplicated(). Поскольку это грубые дубликаты, то есть повторы, полученные скорее всего, при копировании информации, избавимся от них с изменением индексов и удалением старых строк. Новая таблица с данными стала на 54 строки (дубликата) короче.


<div style="border:solid red 2px; padding: 20px"> <h1 style="color:red; margin-bottom:20px">Комментарий ревьюера - 2</h1>
    
Посмотри на столбец education там нужно выполнить определенные преобразования после этих преобразований дублей станет больше.

Не стоит выводить голые числа. Делай print и  лучше делать подпись, чтоб было сразу понятно, что означают выводимые числа:
    
"Количество дубликатов до удаления: 54"
    
"Количество дубликатов псоле удаления: 0"

</div>

### Ответ_2
Мы в ручную привели значения уровня образования к следующим записям: среднее / высшее / неоконченное высшее / начальное / ученая степень.
У нас появилось 17 строк с идентичной информацией методом. иИзбавимся от них с изменением индексов и удалением старых строк.

### Шаг 5. Проводим лемматизацию

In [5]:
from pymystem3 import Mystem
m = Mystem() 
purpose_lem = df['purpose']
lemmas = []
for row in purpose_lem:
    row = ' '.join(m.lemmatize(row))

    lemmas.append(row)

from collections import Counter
print(Counter(lemmas))

Counter({'автомобиль \n': 967, 'свадьба \n': 790, 'на   проведение   свадьба \n': 762, 'сыграть   свадьба \n': 760, 'операция   с   недвижимость \n': 671, 'покупка   коммерческий   недвижимость \n': 658, 'покупка   жилье   для   сдача \n': 649, 'операция   с   жилье \n': 646, 'операция   с   коммерческий   недвижимость \n': 645, 'покупка   жилье \n': 640, 'жилье \n': 640, 'покупка   жилье   для   семья \n': 637, 'недвижимость \n': 631, 'строительство   собственный   недвижимость \n': 628, 'операция   со   свой   недвижимость \n': 622, 'строительство   жилой   недвижимость \n': 620, 'строительство   недвижимость \n': 619, 'покупка   свой   жилье \n': 619, 'покупка   недвижимость \n': 615, 'ремонт   жилье \n': 604, 'покупка   жилой   недвижимость \n': 602, 'на   покупка   свой   автомобиль \n': 503, 'заниматься   высокий   образование \n': 495, 'сделка   с   подержанный   автомобиль \n': 480, 'свой   автомобиль \n': 473, 'на   покупка   подержать   автомобиль \n': 471, 'на   покупка   ав

### Вывод

Обработав 21 тысячу дубликатов мы получили 6 основных целей кредитов заемщиков:
недвижимость    
автомобиль       
образование     
жилье            
строительство    
свадьба

<div style="border:solid green 2px; padding: 20px"> <h1 style="color:green; margin-bottom:20px">Комментарий ревьюера</h1>

Лемматизация выполнена отлично, правильно, что ты рассмотрел частоту полученных лемм и обосновано выбрал категории для целей кредита. Хотя недвижимость, жилье и строительство можно и объединить
</div>

### Шаг 6. Делаем категоризацию данных

In [6]:
#Выделим самые используемые леммы и систематизируем столбец

def get_purpose(row):
    lem_purpose = m.lemmatize(row['purpose'])
    if 'строительство' in lem_purpose or 'ремонт' in lem_purpose:
        return 'строительство'
    elif 'недвижимость' in lem_purpose:
        return 'недвижимость'    
    elif 'образование' in lem_purpose:
        return 'образование'
    elif 'автомобиль' in lem_purpose:
        return 'автомобиль'
    elif 'свадьба' in lem_purpose:
        return 'свадьба'
    elif 'жилье' in lem_purpose:
        return 'жилье'
    
df['purpose_lemm'] = df.apply(get_purpose, axis = 1)
print('цели кредита:')
print(df['purpose_lemm'].value_counts())
#df.info()

цели кредита:
недвижимость     4444
автомобиль       4277
образование      3987
жилье            3831
строительство    2471
свадьба          2312
Name: purpose_lemm, dtype: int64


<div style="border:solid green 2px; padding: 20px"> <h1 style="color:green; margin-bottom:20px">Комментарий ревьюера</h1>

Хорошо, категории выделены правильно. Но все же в этом разделе стоило выделить все категории, а не только цели. Какие категории нам еще нужны для ответы на вопросы? Не нужно откладывать это на следующий раздел, нужно сделать это здесь
</div>

### Вывод

Выделив 6 основных целей кредитов заемщиков:
[недвижимость    
автомобиль       
образование     
жилье            
строительство    
свадьба]
Теперь мы можем определить факт погашения кредита в срок.

### Шаг 7. Отвечаем на вопросы

- Есть ли зависимость между наличием детей и возвратом кредита в срок?

In [20]:
#df.style.format({'debt': '{:.1%}'})
#rest_children = df[['children','debt']]
#rest_children.style.format({'debt': '{:.1%}'})
#df.style.format("{:.2%}")
#rest_children.style.format({'debt': '{:.2%}'})

#rest_children.style.format({'debt':'{:,.1%}'})
#print(rest_children.groupby('children').mean().sort_values('debt',ascending=False))


#print(rest_children)

new_children = df.groupby('children').debt.agg(debts  = 'sum', total='count')
new_children['perc'] = new_children['debts']/new_children['total']
new_children.style.format({'perc':'{:,.1%}'.format})

#print('Вероятность невозврата кредита, если в семье 4 ребенка: 9.8%')
#print('Вероятность невозврата кредита, если в семье 2 ребенка: 9.5%')
#print('Вероятность невозврата кредита, если в семье 1 ребенка: 9.2%')
#print('Вероятность невозврата кредита, если в семье 3 ребенка: 8.2%')
#print('Вероятность невозврата кредита, если в семье нет детей: 7.5%')
#print('Вероятность невозврата кредита, если в семье 5 детей: 0.0%')

### Вывод

Наличие детей влияет на вероятность невозврата кредита в срок.
Лучше всего отдают кредит у заемщики без детей: вероятность невозврата кредита 7.5%:
Самая большая просрочка по кредитам у заемщиков с 4-мя детьми: вероятность невозврата кредита 9.8%

- Есть ли зависимость между семейным положением и возвратом кредита в срок?

In [24]:
#rest_family_status = df[['family_status','debt']]
#print(rest_family_status.groupby('family_status').mean().sort_values('debt',ascending=False))
 
#print('Вероятность невозврата кредита, если заемщик не женат / не замужем: 9.8%')
#print('Вероятность невозврата кредита, если заемщик состоит в гражданском браке: 9.3%')
#print('Вероятность невозврата кредита, если заемщик женат / замужем: 7.6%')
#print('Вероятность невозврата кредита, если заемщик в разводе: 7.1%')
#print('Вероятность невозврата кредита, если заемщик вдовец / вдова: 6.6%')

new_family = df.groupby('family_status').debt.agg(debts  = 'sum', total='count')
new_family['famil'] = new_family['debts']/new_family['total']
new_family.style.format({'famil':'{:,.1%}'.format})


### Вывод

Семейное положение влияет на вероятность невозврата кредита в срок. 
Вероятность невозврата кредита в срок находится в пределах 6.6 - 9.8%:
Самые ответственные заемщики - если заемщик вдовец / вдова (вероятность невозврата кредита 6.6%).
Самые безответственные заемщики - заемщики, которые не женаты / не замужем (вероятность невозврата кредита 9.8%).

- Есть ли зависимость между уровнем дохода и возвратом кредита в срок?

In [26]:
income_debt_group = df.loc[:, ['total_income', 'debt']]

def group_income(row):
    alert_group_ti = row['total_income']
    im_income = row['debt']

    if alert_group_ti <= 120000:
        if im_income == 0:
            return 'низкий доход, НЕТ задолженности'

    if alert_group_ti <= 120000:
        if im_income == 1:
            return 'низкий доход, ЕСТЬ задолженность'

    if 120000 <= alert_group_ti <= 180000:
        if im_income == 0:
            return 'средний доход, НЕТ задолженности'
 
    if 120000 <= alert_group_ti <= 180000:
        if im_income == 1:
            return 'средний доход, ЕСТЬ задолженность'

    if alert_group_ti >= 180000:
        if im_income == 0:
            return 'высокий доход, НЕТ задолженности'
 
         
    return 'высокий доход, ЕСТЬ задолженность'


row_columns_ti = ['total_income', 'debt']
row = pd.Series(index=row_columns_ti)
income_debt_group['total_income'] = income_debt_group.apply(group_income, axis=1)
#print(income_debt_group['total_income'].value_counts()) 


dohod_niz_net = income_debt_group[income_debt_group['total_income'] == 'низкий доход, НЕТ задолженности']['total_income'].count()
#print(dohod_niz_net)
dohod_niz_est = income_debt_group[income_debt_group['total_income'] == 'низкий доход, ЕСТЬ задолженность']['total_income'].count()
#print(dohod_niz_est)
dohod_sr_net = income_debt_group[income_debt_group['total_income'] == 'средний доход, НЕТ задолженности']['total_income'].count()
#print(dohod_sr_net)
dohod_sr_est = income_debt_group[income_debt_group['total_income'] == 'средний доход, ЕСТЬ задолженность']['total_income'].count()
#print(dohod_sr_est)
dohod_vys_net = income_debt_group[income_debt_group['total_income'] == 'высокий доход, НЕТ задолженности']['total_income'].count()
#print(dohod_vys_net)
dohod_vys_est = income_debt_group[income_debt_group['total_income'] == 'высокий доход, ЕСТЬ задолженность']['total_income'].count()
#print(dohod_vys_est)

per_niz_dohod = dohod_niz_est / (dohod_niz_net + dohod_niz_est)
print('Вероятность невозврата кредита, если доход до 120 тыс.: {:.1%}'.format(per_niz_dohod))
per_sr_dohod = dohod_sr_est / (dohod_sr_net + dohod_sr_est)
print('Вероятность невозврата кредита, если доход в пределах от 120 тыс. до 180 тыс.: {:.1%}'.format(per_sr_dohod))
per_vys_dohod = dohod_vys_est / (dohod_vys_net + dohod_vys_est)
print('Вероятность невозврата кредита, если доход от 180 тыс.: {:.1%}'.format(per_vys_dohod))



Вероятность невозврата кредита, если доход до 120 тыс.: 8.1%
Вероятность невозврата кредита, если доход в пределах от 120 тыс. до 180 тыс.: 8.9%
Вероятность невозврата кредита, если доход от 180 тыс.: 7.5%


### Вывод

Уровень дохода влияет на вероятность невозврата кредита в срок. 
Вероятность невозврата кредита в срок находится в пределах 7.4 - 8.9%:
Самые ответственные заемщики с уровнем дохода от 180 тыс. с вероятностью невозврата кредита в 7.4%, далее идут заемщики, которые имеют доход до 120 тыс. с вероятностью невозврата кредита в 8.1%.
Самые безответственные заемщики с доходом от 120 до 180 тыс. с вероятностью невозврата кредита в 8.9%

- Как разные цели кредита влияют на его возврат в срок?

In [25]:
#rest_purpose = df[['purpose_lemm','debt']]
#abcd = rest_purpose.groupby('purpose_lemm').mean().sort_values('debt',ascending=False)


#print(rest_purpose.groupby('purpose_lemm').mean().sort_values('debt',ascending=False))

#print('Вероятность невозврата кредита, если кредит на автомобиль: 9.3%')
#print('Вероятность невозврата кредита, если кредит на образование: 9.3%')
#print('Вероятность невозврата кредита, если кредит на свадьбу: 7.9%')
#print('Вероятность невозврата кредита, если кредит на недвижимость: 7.4%')
#print('Вероятность невозврата кредита, если кредит на строительство: 7.2%')
#print('Вероятность невозврата кредита, если кредит на жилье: 7.1%')
new_p_l = df.groupby('purpose_lemm').debt.agg(debts  = 'sum', total='count')
new_p_l['famil'] = new_p_l['debts']/new_p_l['total']
new_p_l.style.format({'famil':'{:,.1%}'.format})

<div style="border:solid red 2px; padding: 20px"> <h1 style="color:red; margin-bottom:20px">Комментарий ревьюера - 3</h1>

Да, так уже лучше. Но не нужно делать print  в конце, так весь смысл теряется.
    
    
Отформатируй, пожалуйста полученные результаты в таблице в виде процентов с 1 знаком после запятой.
    
В таблице с детьми нужно отбросить аномальные данные
    
Также нужно доделать вопрос про доход
</div>

### Ответ_3
Аномальные данные отброшены, результаты в процентах, выводы поправлены, по доходу слетел код, тоже поправлен

### Вывод

Цели кредита влияют на вероятность невозврата кредита в срок. 
Вероятность невозврата кредита в срок находится в пределах 7.1 - 9.3%.
Можно выделить 2 группы с одинаковой вероятностью невозврата кредита в срок:
- самые ответственные заемщики с целями на жилье, строительство, недвижимость и свадьбу с вероятностью невозврата кредита в срок соответственно 7.1, 7.2%, 7.4% и 7.9%.
- самые безответственные заемщики с целями на автомобиль, образование с вероятностью невозврата кредита в срок соответственно 9.3%.

Цели кредита не влияют на возврат кредита в срок. Число кредитов с задолженностью составляет около 10%.

<div style="border:solid red 2px; padding: 20px"> <h1 style="color:red; margin-bottom:20px">Комментарий ревьюера</h1>

Ответы на вопросы сделаны не правильно.
    
Здесь нужно рассчитать вероятность невозврата кредита для каждой категории. Т.е. отношение просрочек к общему числу группы. 
    
В итоге должны получится таблицы с категориями и веротностями просрочки и уже из этого нужно делать выводы
</div>

<div style="border:solid red 2px; padding: 20px"> <h1 style="color:red; margin-bottom:20px">Комментарий ревьюера - 2</h1>

Ты используешь не верный подход для получения результата. Твой спомоб может сработать для небольшого числа категорий. А если их больше, если их 100, 500, 100500? Так не пойдет
    
Здесь нужно использовать сводную таблицу pivot_table или groupby. В этой таблице для каждой группы нужно получить количество 0 и 1 в столбце debt. Пот ом надо в этой же таблице рассчитать вероятность.
</div>

<div style="border:solid green 2px; padding: 20px"> <h1 style="color:green; margin-bottom:20px">Комментарий ревьюера - 3</h1>

Да, вот теперь это автоматизированный рассчет
</div>

### Ответ_2
Да, согласен, что немного усложнил этот процесс, т.к. в первой версии не знал что необходимо выводить вероятность возврата кредита. Ну а потом что средее значение через debt методом groupby и будет эта вероятность.
При опаределении заемщиков по уровню доходов оставил прошлый вариант, тк разбиваем всего на 3 группы. 

### Шаг 8. Делаем общий вывод

Проанализировав исходные данные от отдела банка, делаем вывод, что цели кредита, Уровень дохода, семейное положение и к оличество детейне влияют на возврат кредита в срок. Число кредитов с задолженностью во всех случаях составляет около 10%.

<div style="border:solid green 2px; padding: 20px"> <h1 style="color:green; margin-bottom:20px">Комментарий ревьюера</h1>

Хорошо, портрет надежного заемщика - это важно (с поправкой на неверный рассчет в предыдущем пункте). Но в итоговых выводах стоит описать все аспекты проекта. Например, наличие пропусков и дубликатов в данных также может быть важно для клиента. Это может означать не верный сбор данных или даже мошенничество...
</div> 

# Ответ
В исходных данных от отдела банка мы получили данные по 21525 заемщикам. 2175 в столбцах "общий трудовой стаж в днях" и "ежемесячный доход" оказались пропущены, а это составляет 10% от общего числа. Данные значения были заменены на медианные. 123 значения в столбце "количество детей в семье" были ошибочные и содержали отрицательные значения или неправдоподобно большие и были удалены (0,6% от общего числа данных). Также были выявлены дубликаты в 54-х строках и также были удалены. После обработки столбца education были выявлены еще 17 дубликатов, которые были удалены. Суммарно число удаленых строк составляет менее 1% и не влияет на результаты анализа.
По результатам анализа данных банка было определено, что наличие детей, семейное положение, уровень доходов и цели кредита влияют на вероятность невозврата кредита в срок (она находится в пределах 6.6-9.8%).
самыми надежными заемщиками оказались заемщики без детей, вдовец / вдова, с доходом от 180 тыс. и целью кредита недвижимость/жилье/строительство/свадьба.
Самыми ненадежными заемщиками оказались заемщики с 4-мя детьми, не женаты / не замужем, с доходом от 120 до 180 тыс. и целью кредита автомобиль/образование.

<div style="border:solid green 2px; padding: 20px"> <h1 style="color:green; margin-bottom:20px">Общий комментарий по проекту</h1>

В целом проет выполнен хорошо, отлично сделана предобработка, но в рассчетах немного запутался. Ты  недоработал ответы на вопросы, постарайся поправить. Также постарайся, пожалуйста учесть не только красные, но и желтые комментарии, это улучшит проект. Удачи
</div>

### Чек-лист готовности проекта

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  открыт файл;
- [x]  файл изучен;
- [x]  определены пропущенные значения;
- [x]  заполнены пропущенные значения;
- [x]  есть пояснение, какие пропущенные значения обнаружены;
- [x]  описаны возможные причины появления пропусков в данных;
- [x]  объяснено, по какому принципу заполнены пропуски;
- [x]  заменен вещественный тип данных на целочисленный;
- [x]  есть пояснение, какой метод используется для изменения типа данных и почему;
- [x]  удалены дубликаты;
- [x]  есть пояснение, какой метод используется для поиска и удаления дубликатов;
- [x]  описаны возможные причины появления дубликатов в данных;
- [x]  выделены леммы в значениях столбца с целями получения кредита;
- [x]  описан процесс лемматизации;
- [x]  данные категоризированы;
- [x]  есть объяснение принципа категоризации данных;
- [x]  есть ответ на вопрос: "Есть ли зависимость между наличием детей и возвратом кредита в срок?";
- [x]  есть ответ на вопрос: "Есть ли зависимость между семейным положением и возвратом кредита в срок?";
- [x]  есть ответ на вопрос: "Есть ли зависимость между уровнем дохода и возвратом кредита в срок?";
- [x]  есть ответ на вопрос: "Как разные цели кредита влияют на его возврат в срок?";
- [x]  в каждом этапе есть выводы;
- [x]  есть общий вывод.